server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka,http://localhost:8080/eureka,http://localhost:8081/eureka,http://localhost:8888/eureka 