# 页面默认前缀目录
#spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp # 响应页面默认后缀
############################################################
#freemarker settings
############################################################
#spring:
  #freemarker:
    #template-loader-path: classpath:/templates
   # cache: false #change to true for production
   # charset: UTF-8
   # check-template-location: true
   # content-type: text/html
   # expose-request-attributes: true
   # expose-session-attributes: true
   # request-context-attribut: request
   # suffix: ftl
#  mvc:
#    static-path-pattern: /static/**
############################################################
server:
  port: 8080
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8082/eureka
      
      
      
      
      
      
      
      
      
      